# -*- coding: utf-8 -*-
"""data_cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYzTVnFrnGH-WpyZq4yWpNgSZZW4tgYs
"""

class DataCleaner:
  def __init__(self, df):
    self.df = df
  def remove_nulls(self):
    self.df = self.df.dropna()
  def fix_dtypes(self):
    self.df["Order Date"] = pd.to_datetime(
        self.df["Order Date"],
        dayfirst=True
    )

    self.df["Ship Date"] = pd.to_datetime(
        self.df["Ship Date"],
        dayfirst=True
    )

    self.df["Postal Code"] = self.df["Postal Code"].astype(str)
  def get_clean_df(self):
    return self.df.copy()
  def remove_duplicates(self):
    self.df = self.df.drop_duplicates()
  def encode_categoricals(self):
    self.df["ShipMode_Encoded"] = (self.df["Ship Mode"].astype("category").cat.codes)
    self.df["Segment_Encoded"] = (self.df["Segment"].astype("category").cat.codes)
    self.df["Region_Encoded"] = (self.df["Region"].astype("category").cat.codes)
    self.df["Category_Encoded"] = (self.df["Category"].astype("category").cat.codes)
    self.df["SubCategory_Encoded"] = (self.df["Sub-Category"].astype("category").cat.codes)