# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYzTVnFrnGH-WpyZq4yWpNgSZZW4tgYs
"""

class DataLoader:
    def __init__(self, file_path):
        self.file_path = file_path
        self.df = None
    def load_csv(self):
        self.df = pd.read_csv(self.file_path, encoding="latin1", on_bad_lines="skip")
        return self.df
    def validate_schema(self):
        Datasett_col = [
            "Row ID",
            "Order ID",
            "Order Date",
            "Ship Date",
            "Ship Mode",
            "Customer ID",
            "Customer Name",
            "Segment",
            "Country",
            "City",
            "State",
            "Postal Code",
            "Region",
            "Product ID",
            "Category",
            "Sub-Category",
            "Product Name",
            "Sales",
            "Quantity",
            "Discount",
            "Profit",
        ]

        for col in Datasett_col:
            if col not in self.df.columns:
                raise ValueError

        # def validate_schema(self):
        #     print("Schema its ok!")

    def get_raw_df(self):
        return self.df.copy()