# -*- coding: utf-8 -*-
"""Feature Importance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17evbcJKvVZI5pHfKs-CsMsp5-dQT3DYC
"""

from scipy.stats import pearsonr
features = [
    "Sales",
    "Quantity",
    "Discount",
    "ProfitMargin"
]
corr_values = []

for col in features:
    corr, _ = pearsonr(df[col], df["Profit"])
    corr_values.append(corr)
plt.figure(figsize=(8,5))
plt.bar(features, corr_values)
plt.title("Feature Importance")
plt.ylabel("Correlation")
plt.xticks(rotation=45)
plt.show()