# -*- coding: utf-8 -*-
"""feature_engineer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYzTVnFrnGH-WpyZq4yWpNgSZZW4tgYs
"""

class FeatureEngineer:
  def __init__(self, df):
    self.df = df
  def add_month_year(self):
    self.df["Month"] = self.df["Order Date"].dt.month
    self.df["Year"] = self.df["Order Date"].dt.year
  def add_profit_margin(self):
    self.df["ProfitMargin"] = self.df["Profit"] / self.df["Sales"]
  def aggregate_monthly(self):
    monthly_sales = (self.df.groupby(["Year", "Month"])["Sales"].sum().reset_index())
    return monthly_sales
  def create_profit_label(self):
    self.df["Profit_Label"] = (self.df["Profit"] > 0).astype(int)