# -*- coding: utf-8 -*-
"""knn_classifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuDXF3k1MPdA4s54CWL-v9fpzpAONzKm
"""

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X = df[[
        "Sales",
        "Quantity",
        "Discount",
        "ProfitMargin"]]
y = df["Profit_Label"]
X_train, X_test, y_train, y_test = (train_test_split(X, y, test_size=0.2, random_state=42))
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

class KNNClassifier:
    def __init__(self):
        self.model = None
        self.x_test = None
        self.y_test = None
    def train(self, x_train, y_train, x_test, y_test, k=3):
        self.model = KNeighborsClassifier(n_neighbors=k)
        self.model.fit(x_train, y_train)
        self.x_test = x_test
        self.y_test = y_test
        return self.model
    def predict(self):
        return self.model.predict(self.x_test)
    def confusion_matrix(self):
        y_pred = self.predict()
        cm = confusion_matrix(self.y_test, y_pred)
        return cm
    def accuracy(self):
        y_pred = self.predict()
        acc = accuracy_score(self.y_test, y_pred)
        print(f"Accuracy: {acc:.4f}")
        return acc

for k in [3, 5, 7]:
    print(f"\nK = {k}")
    knn = KNNClassifier()
    knn.train(X_train, y_train, X_test, y_test, k=k)
    knn.accuracy()
    print(knn.confusion_matrix())

import seaborn as sns
import matplotlib.pyplot as plt

cm = knn.confusion_matrix()
plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt="d")
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()