# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuDXF3k1MPdA4s54CWL-v9fpzpAONzKm
"""

if __name__ == "__main__":

    loader = DataLoader("Superstore.csv")
    loader.load_csv()

    cleaner = DataCleaner(loader.get_raw_df())
    cleaner.remove_nulls()
    cleaner.remove_duplicates()
    cleaner.fix_dtypes()
    cleaner.encode_categoricals()

    df = cleaner.get_clean_df()

    fe = FeatureEngineer(df)
    fe.add_month_year()
    fe.add_profit_margin()
    fe.create_profit_label()

    df = fe.df

    pipeline = ReportPipeline(df)
    pipeline.generate_csv()