# -*- coding: utf-8 -*-
"""regression_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYzTVnFrnGH-WpyZq4yWpNgSZZW4tgYs
"""

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
class RegressionModel:

    def __init__(self, monthly_df):
        self.df = monthly_df
        X = self.df[["Year", "Month"]]
        y = self.df["Sales"]
        self.X_train, self.X_test, self.y_train, self.y_test = (train_test_split(X, y, test_size=0.2, random_state=42))
        self.linear_model = None
        self.poly_models = {}
        self.poly_predictions = {}
    def train_linear(self):
        self.linear_model = LinearRegression()
        self.linear_model.fit(self.X_train, self.y_train)
        self.linear_pred = (self.linear_model.predict(self.X_test))
        return self.linear_model
    def train_polynomial(self, degree=2):
        poly = PolynomialFeatures(degree=degree)
        X_train_poly = poly.fit_transform(self.X_train)
        X_test_poly = poly.transform(self.X_test)
        model = LinearRegression()
        model.fit(X_train_poly, self.y_train)
        predictions = (model.predict(X_test_poly))
        self.poly_models[degree] = (model, poly)
        self.poly_predictions[degree] = (predictions)
        return model
    def evaluate(self):
        results = {}
        linear_mse = mean_squared_error(self.y_test, self.linear_pred)
        results["Linear"] = linear_mse
        print(
            f"Linear Regression MSE: "
            f"{linear_mse:.2f}")

        for degree, preds in (self.poly_predictions.items()):
            mse = mean_squared_error(self.y_test, preds)
            results[f"Polynomial Degree {degree}"] = mse
            print(
                f"Polynomial Degree {degree} "
                f"MSE: {mse:.2f}")
        best_model = min(results, key=results.get)
        print(
            f"\nBest Model: "
            f"{best_model}")
        return results

    def plot_predictions(self):
        plt.figure(figsize=(12, 6))
        plt.plot(range(len(self.y_test)), self.y_test.values, marker="o", label="Actual Sales")
        plt.plot(range(len(self.linear_pred)), self.linear_pred, marker="x", label="Linear Regression")
        for degree, preds in (self.poly_predictions.items()):
            plt.plot(range(len(preds)), preds, marker="s", label=f"Polynomial Degree {degree}")
        plt.title("Actual vs Predicted Sales")
        plt.xlabel("Test Samples")
        plt.ylabel("Sales")
        plt.legend()
        plt.grid(True)
        plt.show()

    def plot_mse_comparison(self):
        mse_values = {}
        mse_values["Linear"] = (mean_squared_error(self.y_test, self.linear_pred))
        for degree, preds in (
            self.poly_predictions.items()):
            mse_values[f"Poly {degree}"] = (mean_squared_error(self.y_test, preds))
        plt.figure(figsize=(8, 5))
        plt.bar(mse_values.keys(), mse_values.values())
        plt.title("MSE Comparison")
        plt.ylabel("Mean Squared Error")
        plt.show()