# -*- coding: utf-8 -*-
"""ReportPipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuDXF3k1MPdA4s54CWL-v9fpzpAONzKm
"""

class ReportPipeline:

    def __init__(self, df):
        self.df = df
    def run_all(self):
        analyzer = SalesAnalyzer(self.df)
        print(analyzer.top_products())
        print(analyzer.sales_by_region())
        analyzer.plot_summary()
    def save_results(self, results):
        with open("results.txt", "w", encoding="utf-8") as f:
            for key, value in results.items():
                f.write(f"{key}: {value}\n")
        print("ok")
    def generate_csv(self):
        self.df.to_csv("Superstore_data.csv",index=False)
        print("ok :)")
pipeline = ReportPipeline(df)
pipeline.generate_csv()

from google.colab import files
files.download("Superstore_data.csv")