# -*- coding: utf-8 -*-
"""sales_analyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uYzTVnFrnGH-WpyZq4yWpNgSZZW4tgYs
"""
class SalesAnalyzer:
  def __init__(self,df):
    self.df = df
  def top_products(self):
    top_productss = (self.df.groupby(["Product Name"])["Sales"].sum().sort_values(ascending = False).head())
    return top_productss
  def sales_by_region(self):
    region_sales = (self.df.groupby("Region")["Sales"].sum().sort_values(ascending = False))
    return region_sales
  def monthly_trend(self):
    trend_months = (self.df.groupby(["Year", "Month"])["Sales"].sum())
    return trend_months
  def plot_summary(self):
    self.top_products().plot(kind = "bar", figsize = (10, 5), title = "Top products by sales")
    plt.show()
    self.sales_by_region().plot(kind = "bar", figsize = (10, 5), title = "Top sales by region")
    plt.show()
    monthly = self.monthly_trend()
    plt.figure(figsize=(10, 5))
    plt.plot(range(len(monthly)), monthly)
    plt.title("Monthly Sales Trend")
    plt.xlabel("Month")
    plt.ylabel("Sales")
    plt.show()
  def plot_heatmap(self):
    corr = self.df[
        [
            "Sales",
            "Quantity",
            "Discount",
            "Profit"
        ]
    ].corr()
    plt.figure(figsize=(8,5))
    sns.heatmap(corr,annot=True)
    plt.title("Sales Correlation Heatmap")
    plt.show()

analyzer = SalesAnalyzer(df)
analyzer.plot_summary()
analyzer.plot_heatmap()
