# -*- coding: utf-8 -*-
"""visualizer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GuDXF3k1MPdA4s54CWL-v9fpzpAONzKm
"""

class Visualizer:
    def plot_regression(self, y_test, predictions):
        plt.figure(figsize=(10,5))
        plt.plot(y_test.values, label="Actual")
        plt.plot(predictions, label="Predicted")
        plt.legend()
        plt.show()
    def plot_knn_boundary(self, cm):
        plt.figure(figsize=(5,4))
        sns.heatmap(cm, annot=True, fmt="d")
        plt.title("Confusion Matrix")
        plt.show()